# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a06bd4e8518c9a453beb0506efbf1abcb9e2e88f43610e84cff8ab9df20b92b560c463785f5f50bd2f36a7f998aca00a7a8b3019215ccf67a72e88129c1ea63

test:
  secret_key_base: 10d48851c24faa8dcf9d32f6e576bda79ac0ae223d584e4a99a7acb95885861ce73a11d9761f0414978d091852da6b84c254bb4e7eebec9c953444da9512bf14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
